In [1]:
pip install yfinance

Requirement already satisfied: yfinance in /Users/seanmorey/opt/anaconda3/lib/python3.7/site-packages (0.1.55)
Requirement already satisfied: multitasking>=0.0.7 in /Users/seanmorey/opt/anaconda3/lib/python3.7/site-packages (from yfinance) (0.0.9)
Requirement already satisfied: pandas>=0.24 in /Users/seanmorey/opt/anaconda3/lib/python3.7/site-packages (from yfinance) (1.1.5)
Requirement already satisfied: lxml>=4.5.1 in /Users/seanmorey/opt/anaconda3/lib/python3.7/site-packages (from yfinance) (4.6.2)
Requirement already satisfied: requests>=2.20 in /Users/seanmorey/opt/anaconda3/lib/python3.7/site-packages (from yfinance) (2.22.0)
Requirement already satisfied: numpy>=1.15 in /Users/seanmorey/opt/anaconda3/lib/python3.7/site-packages (from yfinance) (1.18.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/seanmorey/opt/anaconda3/lib/python3.7/site-packages (from pandas>=0.24->yfinance) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /Users/seanmorey/opt/anaconda3/lib/python3.7/site-packages (from pandas>=0.24->yfinance) (2019.3)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/seanmorey/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /Users/seanmorey/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/seanmorey/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/seanmorey/opt/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (3.0.4)
Requirement already satisfied: six>=1.5 in /Users/seanmorey/opt/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance) (1.14.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [11]:
stock_list = ["MLR","HCA","LPX", "KO", "PEP", "GS", "JPM"]
stock = "SPY"
period = "60d"
interval = "30m"
stock1 = yf.Ticker(stock)
stock1_price = stock1.history(period=period, interval=interval)
stock1_df = pd.DataFrame(stock1_price.Close).rename(columns={"Close": stock})
df = stock1_df

for stock in stock_list:
    print("Starting stock: ", stock)
    stock2 = yf.Ticker(stock)
    print("Got stock: ", stock)
    stock2_price = stock2.history(period=period, interval=interval)
    stock2_df = pd.DataFrame(stock2_price.Close).rename(columns={"Close": stock})
    df = df.merge(stock2_df, left_on='Datetime', right_on='Datetime')
    
df.head()

Starting stock:  MLR
Got stock:  MLR
Starting stock:  HCA
Got stock:  HCA
Starting stock:  LPX
Got stock:  LPX
Starting stock:  KO
Got stock:  KO
Starting stock:  PEP
Got stock:  PEP
Starting stock:  GS
Got stock:  GS
Starting stock:  JPM
Got stock:  JPM

,SPY,MLR,HCA,LPX,KO,PEP,GS,JPM
Datetime,,,,,,,,
2020-12-01 09:30:00-05:00,366.160095,33.910000,152.750000,34.799999,51.849998,145.164993,234.440002,120.695000
2020-12-01 10:00:00-05:00,366.975586,34.410000,152.729996,34.849998,52.230000,145.880005,234.210007,120.589996
2020-12-01 10:30:00-05:00,366.290009,34.270000,152.470001,34.669998,52.169998,145.800003,233.750000,120.830002
2020-12-01 11:00:00-05:00,366.649994,34.029999,151.925003,34.549999,52.143501,145.789993,234.419998,121.190002
2020-12-01 11:30:00-05:00,366.269897,33.860001,151.279999,34.400002,52.110001,145.589996,232.549698,120.400002

In [16]:
df.corr()

,SPY,MLR,HCA,LPX,KO,PEP,GS,JPM
SPY,1.000000,0.863566,0.852278,0.761471,-0.670492,-0.778872,0.888290,0.880197
MLR,0.863566,1.000000,0.789806,0.615806,-0.803815,-0.716290,0.892889,0.823459
HCA,0.852278,0.789806,1.000000,0.766500,-0.536631,-0.680718,0.888575,0.855842
LPX,0.761471,0.615806,0.766500,1.000000,-0.382307,-0.874865,0.773139,0.807672
KO,-0.670492,-0.803815,-0.536631,-0.382307,1.000000,0.649381,-0.707927,-0.649696
PEP,-0.778872,-0.716290,-0.680718,-0.874865,0.649381,1.000000,-0.827459,-0.850878
GS,0.888290,0.892889,0.888575,0.773139,-0.707927,-0.827459,1.000000,0.980389
JPM,0.880197,0.823459,0.855842,0.807672,-0.649696,-0.850878,0.980389,1.000000

In [67]:
period = "60d"
interval = "5m"
stock = yf.Ticker("JPM")
df = stock.history(period=period, interval=interval)

df = df.replace(to_replace = 0, value =1) 
df = df.drop(['Dividends','Stock Splits'], axis = 1)

cols_pct_change = ["Close", "Volume"]
col_names = []

def target(future_close_pc):
    if future_close_pc >= .001:
        return 1
    else:
        return 0

for col in cols_pct_change:
    for i in np.arange(1,5):
        col_name = f"{col}_{i}p_pc"
        df[col_name] = df[col].pct_change(periods=i)*100
        col_names.append(col_name)
    for i in np.arange(-4, 0):
        if col == "Close":
            df[f"{col}_f{-i}p_pc"] = df[col].pct_change(periods=i)*100
            df[f"y{-i}"] = df[col].pct_change(periods=i).apply(target)

df = df.dropna() 
print(df.shape)
df.head()

(4635, 21)

,Open,High,Low,Close,Volume,Close_1p_pc,Close_2p_pc,Close_3p_pc,Close_4p_pc,Close_f4p_pc,...,Close_f3p_pc,y3,Close_f2p_pc,y2,Close_f1p_pc,y1,Volume_1p_pc,Volume_2p_pc,Volume_3p_pc,Volume_4p_pc
Datetime,,,,,,,,,,,,,,,,,,,,,
2020-12-01 09:50:00-05:00,120.279999,120.750000,120.129997,120.544998,248600,0.211985,0.070644,0.037343,0.613472,-0.103753,...,-0.004152,0,-0.301882,0,-0.124281,0,21.686776,4.454220,-0.067533,-62.965004
2020-12-01 09:55:00-05:00,120.519997,120.779999,120.390099,120.695000,248477,0.124436,0.336685,0.195169,0.161825,0.008288,...,0.020555,0,0.120279,1,-0.177821,0,-0.049477,21.626569,4.402540,-0.116976
2020-12-01 10:00:00-05:00,120.690002,120.959999,120.580002,120.910004,144652,0.178138,0.302796,0.515423,0.373654,-0.066116,...,0.186441,1,0.198729,1,0.298632,1,-41.784551,-41.813355,-29.194547,-39.221593
2020-12-01 10:05:00-05:00,120.915001,120.915001,120.519997,120.550003,125575,-0.297743,-0.120135,0.004152,0.216146,-0.033165,...,-0.363662,0,-0.111857,0,-0.099605,0,-13.188203,-49.462123,-49.487128,-38.532514
2020-12-01 10:10:00-05:00,120.553200,120.809998,120.529999,120.670197,115883,0.099704,-0.198335,-0.020550,0.103860,-0.037858,...,0.066507,0,-0.264320,0,-0.012264,0,-7.718097,-19.888422,-53.362685,-53.385760

In [85]:
KO= yf.Ticker("GME")
KO.option_chain("2021-03-05")

Options(calls=         contractSymbol       lastTradeDate  strike  lastPrice    bid    ask  \
0    GME210305C00020000 2021-02-26 20:39:37    20.0      83.25  78.85  84.10
1    GME210305C00021000 2021-02-26 14:32:25    21.0     115.00  77.85  83.05
2    GME210305C00022000 2021-02-26 19:38:11    22.0      90.00  76.85  82.05
3    GME210305C00023000 2021-02-25 16:10:25    23.0     123.80  75.85  81.05
4    GME210305C00024000 2021-02-25 15:47:24    24.0      96.70  74.85  80.05
..                  ...                 ...     ...        ...    ...    ...
189  GME210305C00720000 2021-02-26 20:59:29   720.0       2.30   2.20   2.65
190  GME210305C00740000 2021-02-26 20:58:26   740.0       2.30   1.64   2.59
191  GME210305C00760000 2021-02-26 20:46:43   760.0       2.20   2.16   2.50
192  GME210305C00780000 2021-02-26 20:57:05   780.0       2.12   2.06   2.24
193  GME210305C00800000 2021-02-26 20:59:52   800.0       2.14   2.12   2.13

        change  percentChange  volume  openInterest  impliedVolatility  \
0    -7.500000      -8.264462      89            38           9.164067
1    21.150002      22.535963       6             0           8.830083
2   -13.000000     -12.621360       3             1           8.566411
3     0.000000       0.000000      22            11           8.320317
4     0.000000       0.000000      25             2           8.083989
..         ...            ...     ...           ...                ...
189  -0.500000     -17.857143     231           446           7.264649
190  -0.200000      -8.000002     313           324           7.172853
191  -0.580000     -20.863306     197           704           7.356446
192  -0.710000     -25.088340    1233           626           7.327149
193  -0.560000     -20.740738   29427          8465           7.376954

     inTheMoney contractSize currency
0          True      REGULAR      USD
1          True      REGULAR      USD
2          True      REGULAR      USD
3          True      REGULAR      USD
4          True      REGULAR      USD
..          ...          ...      ...
189       False      REGULAR      USD
190       False      REGULAR      USD
191       False      REGULAR      USD
192       False      REGULAR      USD
193       False      REGULAR      USD

[194 rows x 14 columns], puts=         contractSymbol       lastTradeDate  strike  lastPrice     bid  \
0    GME210305P00020000 2021-02-26 20:53:11    20.0       0.11    0.09
1    GME210305P00021000 2021-02-26 20:45:25    21.0       0.16    0.15
2    GME210305P00022000 2021-02-26 20:44:22    22.0       0.12    0.18
3    GME210305P00023000 2021-02-26 20:44:23    23.0       0.25    0.20
4    GME210305P00024000 2021-02-26 20:49:06    24.0       0.25    0.20
..                  ...                 ...     ...        ...     ...
172  GME210305P00700000 2021-02-25 18:11:49   700.0     544.80  599.60
173  GME210305P00720000 2021-02-26 17:33:22   720.0     628.58  619.50
174  GME210305P00760000 2021-02-25 19:33:27   760.0     619.75  659.40
175  GME210305P00780000 2021-02-25 18:34:50   780.0     671.80  679.30
176  GME210305P00800000 2021-02-26 20:52:41   800.0     699.90  699.30

        ask     change  percentChange  volume  openInterest  \
0      0.11   0.010000       9.999998  3958.0         17395
1      0.16  -0.100000     -38.461536   441.0          1542
2      0.25  -0.180000     -60.000004   240.0          1695
3      0.25  -0.060000     -19.354840   412.0           687
4      0.25  -0.080000     -24.242428   367.0           658
..      ...        ...            ...     ...           ...
172  603.80   0.000000       0.000000    10.0            21
173  623.70  64.380005      11.410848     1.0            23
174  663.70   0.000000       0.000000    32.0            21
175  683.60  51.200012       8.250083     3.0            24
176  703.60  -0.099976      -0.014282    10.0            29

     impliedVolatility  inTheMoney contractSize currency
0             5.039066       False      REGULAR      USD
1             5.187504       False      REGULAR      USD
2             5.281253       False      REGULAR      USD
3             5.164066       False      REGULAR      USD
4             5.019535       False      REGULAR      USD
..                 ...         ...          ...      ...
172           7.649415        True      REGULAR      USD
173           7.683594        True      REGULAR      USD
174           7.805664        True      REGULAR      USD
175           7.831055        True      REGULAR      USD
176           7.897461        True      REGULAR      USD

[177 rows x 14 columns])

In [54]:
#BROKE AF
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

model = LinearRegression()


X = df[['Open','High','Low','Close','Volume'] + col_names]
y = df['Close_f1p_pc']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

model.fit(X_train, y_train)

predictions = model.predict(X_test)
MSE = mean_squared_error(y_test, predictions)
r2 = model.score(X_test, y_test)

print(f"MSE: {MSE}, R2: {r2}")
print(predictions)
print(model.coef_)

MSE: 286.9180493162504, R2: -7125.5485613029
[-0.01333909 -0.01035271  0.00368163 ...  0.00712869  0.00909585
  0.01561983]
[ 3.10848894e-02 -2.10965361e-02 -1.30874067e-01  1.21033504e-01
 -1.54357876e-07  5.92970937e-02 -2.69886362e-02  5.86905673e-03
  3.19946176e-03  2.35074266e-08  2.39816840e-09 -5.27948021e-05
 -5.64678690e-09]

In [49]:
pd.DataFrame([predictions, y])

,0,1,2,3,4,5,6,7,8,9,...,4625,4626,4627,4628,4629,4630,4631,4632,4633,4634
0,-0.013339,-0.010353,0.003682,0.031997,-0.010284,0.009331,0.018020,-0.013707,0.012692,-0.002064,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.124281,-0.177821,0.298632,-0.099605,-0.012264,-0.252087,0.331704,-0.104295,-0.135755,-0.082663,...,-0.00675,-0.204543,-0.061633,0.067403,-0.067358,0.107885,0.226384,-0.097886,0.054041,-0.168589

In [68]:
from sklearn.svm import SVC

model = SVC(probability=True)


X = df[col_names]
y = df['y1']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

model.fit(X_train, y_train)

predictions = model.predict_proba(X_test)
# MSE = mean_squared_error(y_test, predictions)
r2 = model.score(X_test, y_test)

print(f"MSE: {MSE}, R2: {r2}")
print(predictions)
# print(model.coef_)

MSE: 286.9180493162504, R2: 0.8153580672993961
[[0.80572698 0.19427302]
 [0.80572415 0.19427585]
 [0.80572318 0.19427682]
 ...
 [0.8057241  0.1942759 ]
 [0.80572594 0.19427406]
 [0.80572433 0.19427567]]

In [64]:
df["y1"].mean()

0.19093851132686085